/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AnalyticsQueue": {
      "accountId": string
      "queueId": string
      "type": "cloudflare.index/queue.Queue"
    }
    "AnalyticsWorker": {
      "type": "sst.cloudflare.Worker"
    }
    "AuthApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthStorage": {
      "namespaceId": string
      "type": "sst.cloudflare.Kv"
    }
    "BILLING": {
      "managedServiceMonthlyPriceId": string
      "managedServiceProductId": string
      "managedServiceYearlyPriceId": string
      "meterId": string
      "standard100KMonthlyPriceId": string
      "standard100KOveragePriceId": string
      "standard100KYearlyPriceId": string
      "standard1MMonthlyPriceId": string
      "standard1MOveragePriceId": string
      "standard1MYearlyPriceId": string
      "standard250KMonthlyPriceId": string
      "standard250KOveragePriceId": string
      "standard250KYearlyPriceId": string
      "standard25KMonthlyPriceId": string
      "standard25KOveragePriceId": string
      "standard25KYearlyPriceId": string
      "standard2MMonthlyPriceId": string
      "standard2MOveragePriceId": string
      "standard2MYearlyPriceId": string
      "standard500KMonthlyPriceId": string
      "standard500KOveragePriceId": string
      "standard500KYearlyPriceId": string
      "standard50KMonthlyPriceId": string
      "standard50KOveragePriceId": string
      "standard50KYearlyPriceId": string
      "standard5KMonthlyPriceId": string
      "standard5KOveragePriceId": string
      "standard5KYearlyPriceId": string
      "standardProductId": string
      "type": "sst.sst.Linkable"
    }
    "BillingCronHandler": {
      "type": "sst.cloudflare.Worker"
    }
    "CLOUDFLARE_R2_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_SSL_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ZONE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STORAGE_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "TINYBIRD_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}