/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AuthApi": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
    "PrivateStorage": cloudflare.R2Bucket
    "PublicStorage": cloudflare.R2Bucket
  }
}

import "sst"
export {}