/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAuthorizeRouteImport } from './routes/auth/authorize'
import { Route as WorkspaceWorkspaceIdRouteRouteImport } from './routes/workspace/$workspaceId/route'
import { Route as formFIdRouteImport } from './routes/(form)/f/$id'
import { Route as WorkspaceWorkspaceIdDashboardRouteRouteImport } from './routes/workspace/$workspaceId/_dashboard/route'
import { Route as WorkspaceWorkspaceIdDashboardIndexRouteImport } from './routes/workspace/$workspaceId/_dashboard/index'
import { Route as WorkspaceWorkspaceIdFormsIdLayoutRouteRouteImport } from './routes/workspace/$workspaceId/forms/$id/_layout/route'
import { Route as WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport } from './routes/workspace/$workspaceId/forms/$id/preview/index'
import { Route as WorkspaceWorkspaceIdFormsIdLayoutResponsesRouteImport } from './routes/workspace/$workspaceId/forms/$id/_layout/responses'
import { Route as WorkspaceWorkspaceIdFormsIdLayoutInsightsRouteImport } from './routes/workspace/$workspaceId/forms/$id/_layout/insights'
import { Route as WorkspaceWorkspaceIdFormsIdLayoutEditIndexRouteImport } from './routes/workspace/$workspaceId/forms/$id/_layout/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: '/auth/authorize',
  path: '/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRouteRoute =
  WorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const formFIdRoute = formFIdRouteImport.update({
  id: '/(form)/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdDashboardRouteRoute =
  WorkspaceWorkspaceIdDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdDashboardIndexRoute =
  WorkspaceWorkspaceIdDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdDashboardRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdLayoutRouteRoute =
  WorkspaceWorkspaceIdFormsIdLayoutRouteRouteImport.update({
    id: '/forms/$id/_layout',
    path: '/forms/$id',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdPreviewIndexRoute =
  WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport.update({
    id: '/forms/$id/preview/',
    path: '/forms/$id/preview/',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute =
  WorkspaceWorkspaceIdFormsIdLayoutResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => WorkspaceWorkspaceIdFormsIdLayoutRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute =
  WorkspaceWorkspaceIdFormsIdLayoutInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => WorkspaceWorkspaceIdFormsIdLayoutRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute =
  WorkspaceWorkspaceIdFormsIdLayoutEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => WorkspaceWorkspaceIdFormsIdLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/forms/$id': typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren
  '/workspace/$workspaceId/forms/$id/insights': typeof WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute
  '/workspace/$workspaceId/forms/$id/responses': typeof WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute
  '/workspace/$workspaceId/forms/$id/preview': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
  '/workspace/$workspaceId/forms/$id/edit': typeof WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/forms/$id': typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren
  '/workspace/$workspaceId/forms/$id/insights': typeof WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute
  '/workspace/$workspaceId/forms/$id/responses': typeof WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute
  '/workspace/$workspaceId/forms/$id/preview': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
  '/workspace/$workspaceId/forms/$id/edit': typeof WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/$workspaceId/_dashboard': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/(form)/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/_dashboard/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/forms/$id/_layout': typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren
  '/workspace/$workspaceId/forms/$id/_layout/insights': typeof WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute
  '/workspace/$workspaceId/forms/$id/_layout/responses': typeof WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute
  '/workspace/$workspaceId/forms/$id/preview/': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
  '/workspace/$workspaceId/forms/$id/_layout/edit/': typeof WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$workspaceId'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/f/$id'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/forms/$id'
    | '/workspace/$workspaceId/forms/$id/insights'
    | '/workspace/$workspaceId/forms/$id/responses'
    | '/workspace/$workspaceId/forms/$id/preview'
    | '/workspace/$workspaceId/forms/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/$workspaceId'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/f/$id'
    | '/workspace/$workspaceId/forms/$id'
    | '/workspace/$workspaceId/forms/$id/insights'
    | '/workspace/$workspaceId/forms/$id/responses'
    | '/workspace/$workspaceId/forms/$id/preview'
    | '/workspace/$workspaceId/forms/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/workspace/$workspaceId'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/'
    | '/workspace/$workspaceId/_dashboard'
    | '/(form)/f/$id'
    | '/workspace/$workspaceId/_dashboard/'
    | '/workspace/$workspaceId/forms/$id/_layout'
    | '/workspace/$workspaceId/forms/$id/_layout/insights'
    | '/workspace/$workspaceId/forms/$id/_layout/responses'
    | '/workspace/$workspaceId/forms/$id/preview/'
    | '/workspace/$workspaceId/forms/$id/_layout/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceWorkspaceIdRouteRoute: typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
  formFIdRoute: typeof formFIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/authorize': {
      id: '/auth/authorize'
      path: '/auth/authorize'
      fullPath: '/auth/authorize'
      preLoaderRoute: typeof AuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(form)/f/$id': {
      id: '/(form)/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof formFIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/_dashboard': {
      id: '/workspace/$workspaceId/_dashboard'
      path: ''
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/_dashboard/': {
      id: '/workspace/$workspaceId/_dashboard/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdDashboardRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/_layout': {
      id: '/workspace/$workspaceId/forms/$id/_layout'
      path: '/forms/$id'
      fullPath: '/workspace/$workspaceId/forms/$id'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/preview/': {
      id: '/workspace/$workspaceId/forms/$id/preview/'
      path: '/forms/$id/preview'
      fullPath: '/workspace/$workspaceId/forms/$id/preview'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/_layout/responses': {
      id: '/workspace/$workspaceId/forms/$id/_layout/responses'
      path: '/responses'
      fullPath: '/workspace/$workspaceId/forms/$id/responses'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutResponsesRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/_layout/insights': {
      id: '/workspace/$workspaceId/forms/$id/_layout/insights'
      path: '/insights'
      fullPath: '/workspace/$workspaceId/forms/$id/insights'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutInsightsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/_layout/edit/': {
      id: '/workspace/$workspaceId/forms/$id/_layout/edit/'
      path: '/edit'
      fullPath: '/workspace/$workspaceId/forms/$id/edit'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutEditIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRoute
    }
  }
}

interface WorkspaceWorkspaceIdDashboardRouteRouteChildren {
  WorkspaceWorkspaceIdDashboardIndexRoute: typeof WorkspaceWorkspaceIdDashboardIndexRoute
}

const WorkspaceWorkspaceIdDashboardRouteRouteChildren: WorkspaceWorkspaceIdDashboardRouteRouteChildren =
  {
    WorkspaceWorkspaceIdDashboardIndexRoute:
      WorkspaceWorkspaceIdDashboardIndexRoute,
  }

const WorkspaceWorkspaceIdDashboardRouteRouteWithChildren =
  WorkspaceWorkspaceIdDashboardRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdDashboardRouteRouteChildren,
  )

interface WorkspaceWorkspaceIdFormsIdLayoutRouteRouteChildren {
  WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute
  WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute
  WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute
}

const WorkspaceWorkspaceIdFormsIdLayoutRouteRouteChildren: WorkspaceWorkspaceIdFormsIdLayoutRouteRouteChildren =
  {
    WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute:
      WorkspaceWorkspaceIdFormsIdLayoutInsightsRoute,
    WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute:
      WorkspaceWorkspaceIdFormsIdLayoutResponsesRoute,
    WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute:
      WorkspaceWorkspaceIdFormsIdLayoutEditIndexRoute,
  }

const WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren =
  WorkspaceWorkspaceIdFormsIdLayoutRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdFormsIdLayoutRouteRouteChildren,
  )

interface WorkspaceWorkspaceIdRouteRouteChildren {
  WorkspaceWorkspaceIdDashboardRouteRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  WorkspaceWorkspaceIdFormsIdLayoutRouteRoute: typeof WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren
  WorkspaceWorkspaceIdFormsIdPreviewIndexRoute: typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
}

const WorkspaceWorkspaceIdRouteRouteChildren: WorkspaceWorkspaceIdRouteRouteChildren =
  {
    WorkspaceWorkspaceIdDashboardRouteRoute:
      WorkspaceWorkspaceIdDashboardRouteRouteWithChildren,
    WorkspaceWorkspaceIdFormsIdLayoutRouteRoute:
      WorkspaceWorkspaceIdFormsIdLayoutRouteRouteWithChildren,
    WorkspaceWorkspaceIdFormsIdPreviewIndexRoute:
      WorkspaceWorkspaceIdFormsIdPreviewIndexRoute,
  }

const WorkspaceWorkspaceIdRouteRouteWithChildren =
  WorkspaceWorkspaceIdRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceWorkspaceIdRouteRoute: WorkspaceWorkspaceIdRouteRouteWithChildren,
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
  formFIdRoute: formFIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
