/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAuthorizeRouteImport } from './routes/auth/authorize'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as WorkspaceWorkspaceIdRouteRouteImport } from './routes/workspace/$workspaceId/route'
import { Route as funnelFIdRouteImport } from './routes/(funnel)/f/$id'
import { Route as WorkspaceWorkspaceIdDashboardRouteRouteImport } from './routes/workspace/$workspaceId/_dashboard/route'
import { Route as WorkspaceWorkspaceIdDashboardIndexRouteImport } from './routes/workspace/$workspaceId/_dashboard/index'
import { Route as WorkspaceWorkspaceIdFunnelsIdPreviewRouteImport } from './routes/workspace/$workspaceId/funnels/$id/preview'
import { Route as WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteImport } from './routes/workspace/$workspaceId/funnels/$id/_funnel/route'
import { Route as WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRouteImport } from './routes/workspace/$workspaceId/funnels/$id/_funnel/responses'
import { Route as WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRouteImport } from './routes/workspace/$workspaceId/funnels/$id/_funnel/insights'
import { Route as WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRouteImport } from './routes/workspace/$workspaceId/funnels/$id/_funnel/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: '/auth/authorize',
  path: '/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRouteRoute =
  WorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const funnelFIdRoute = funnelFIdRouteImport.update({
  id: '/(funnel)/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdDashboardRouteRoute =
  WorkspaceWorkspaceIdDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdDashboardIndexRoute =
  WorkspaceWorkspaceIdDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdDashboardRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdPreviewRoute =
  WorkspaceWorkspaceIdFunnelsIdPreviewRouteImport.update({
    id: '/funnels/$id/preview',
    path: '/funnels/$id/preview',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute =
  WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteImport.update({
    id: '/funnels/$id/_funnel',
    path: '/funnels/$id',
    getParentRoute: () => WorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute =
  WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute =
  WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute =
  WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth': typeof AuthIndexRoute
  '/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/funnels/$id': typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren
  '/workspace/$workspaceId/funnels/$id/preview': typeof WorkspaceWorkspaceIdFunnelsIdPreviewRoute
  '/workspace/$workspaceId/funnels/$id/insights': typeof WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute
  '/workspace/$workspaceId/funnels/$id/responses': typeof WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute
  '/workspace/$workspaceId/funnels/$id/edit': typeof WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth': typeof AuthIndexRoute
  '/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId/funnels/$id': typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren
  '/workspace/$workspaceId/funnels/$id/preview': typeof WorkspaceWorkspaceIdFunnelsIdPreviewRoute
  '/workspace/$workspaceId/funnels/$id/insights': typeof WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute
  '/workspace/$workspaceId/funnels/$id/responses': typeof WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute
  '/workspace/$workspaceId/funnels/$id/edit': typeof WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/$workspaceId/_dashboard': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/(funnel)/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId/_dashboard/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/funnels/$id/_funnel': typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren
  '/workspace/$workspaceId/funnels/$id/preview': typeof WorkspaceWorkspaceIdFunnelsIdPreviewRoute
  '/workspace/$workspaceId/funnels/$id/_funnel/insights': typeof WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute
  '/workspace/$workspaceId/funnels/$id/_funnel/responses': typeof WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute
  '/workspace/$workspaceId/funnels/$id/_funnel/edit/': typeof WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$workspaceId'
    | '/api/$'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth'
    | '/f/$id'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/funnels/$id'
    | '/workspace/$workspaceId/funnels/$id/preview'
    | '/workspace/$workspaceId/funnels/$id/insights'
    | '/workspace/$workspaceId/funnels/$id/responses'
    | '/workspace/$workspaceId/funnels/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/$workspaceId'
    | '/api/$'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth'
    | '/f/$id'
    | '/workspace/$workspaceId/funnels/$id'
    | '/workspace/$workspaceId/funnels/$id/preview'
    | '/workspace/$workspaceId/funnels/$id/insights'
    | '/workspace/$workspaceId/funnels/$id/responses'
    | '/workspace/$workspaceId/funnels/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/workspace/$workspaceId'
    | '/api/$'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/'
    | '/workspace/$workspaceId/_dashboard'
    | '/(funnel)/f/$id'
    | '/workspace/$workspaceId/_dashboard/'
    | '/workspace/$workspaceId/funnels/$id/_funnel'
    | '/workspace/$workspaceId/funnels/$id/preview'
    | '/workspace/$workspaceId/funnels/$id/_funnel/insights'
    | '/workspace/$workspaceId/funnels/$id/_funnel/responses'
    | '/workspace/$workspaceId/funnels/$id/_funnel/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceWorkspaceIdRouteRoute: typeof WorkspaceWorkspaceIdRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthIndexRoute: typeof AuthIndexRoute
  funnelFIdRoute: typeof funnelFIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/authorize': {
      id: '/auth/authorize'
      path: '/auth/authorize'
      fullPath: '/auth/authorize'
      preLoaderRoute: typeof AuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(funnel)/f/$id': {
      id: '/(funnel)/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof funnelFIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/_dashboard': {
      id: '/workspace/$workspaceId/_dashboard'
      path: ''
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/_dashboard/': {
      id: '/workspace/$workspaceId/_dashboard/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdDashboardRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/preview': {
      id: '/workspace/$workspaceId/funnels/$id/preview'
      path: '/funnels/$id/preview'
      fullPath: '/workspace/$workspaceId/funnels/$id/preview'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdPreviewRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/_funnel': {
      id: '/workspace/$workspaceId/funnels/$id/_funnel'
      path: '/funnels/$id'
      fullPath: '/workspace/$workspaceId/funnels/$id'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/_funnel/responses': {
      id: '/workspace/$workspaceId/funnels/$id/_funnel/responses'
      path: '/responses'
      fullPath: '/workspace/$workspaceId/funnels/$id/responses'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/_funnel/insights': {
      id: '/workspace/$workspaceId/funnels/$id/_funnel/insights'
      path: '/insights'
      fullPath: '/workspace/$workspaceId/funnels/$id/insights'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/_funnel/edit/': {
      id: '/workspace/$workspaceId/funnels/$id/_funnel/edit/'
      path: '/edit'
      fullPath: '/workspace/$workspaceId/funnels/$id/edit'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute
    }
  }
}

interface WorkspaceWorkspaceIdDashboardRouteRouteChildren {
  WorkspaceWorkspaceIdDashboardIndexRoute: typeof WorkspaceWorkspaceIdDashboardIndexRoute
}

const WorkspaceWorkspaceIdDashboardRouteRouteChildren: WorkspaceWorkspaceIdDashboardRouteRouteChildren =
  {
    WorkspaceWorkspaceIdDashboardIndexRoute:
      WorkspaceWorkspaceIdDashboardIndexRoute,
  }

const WorkspaceWorkspaceIdDashboardRouteRouteWithChildren =
  WorkspaceWorkspaceIdDashboardRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdDashboardRouteRouteChildren,
  )

interface WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteChildren {
  WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute
  WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute
  WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute
}

const WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteChildren: WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteChildren =
  {
    WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute:
      WorkspaceWorkspaceIdFunnelsIdFunnelInsightsRoute,
    WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute:
      WorkspaceWorkspaceIdFunnelsIdFunnelResponsesRoute,
    WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute:
      WorkspaceWorkspaceIdFunnelsIdFunnelEditIndexRoute,
  }

const WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren =
  WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteChildren,
  )

interface WorkspaceWorkspaceIdRouteRouteChildren {
  WorkspaceWorkspaceIdDashboardRouteRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute: typeof WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren
  WorkspaceWorkspaceIdFunnelsIdPreviewRoute: typeof WorkspaceWorkspaceIdFunnelsIdPreviewRoute
}

const WorkspaceWorkspaceIdRouteRouteChildren: WorkspaceWorkspaceIdRouteRouteChildren =
  {
    WorkspaceWorkspaceIdDashboardRouteRoute:
      WorkspaceWorkspaceIdDashboardRouteRouteWithChildren,
    WorkspaceWorkspaceIdFunnelsIdFunnelRouteRoute:
      WorkspaceWorkspaceIdFunnelsIdFunnelRouteRouteWithChildren,
    WorkspaceWorkspaceIdFunnelsIdPreviewRoute:
      WorkspaceWorkspaceIdFunnelsIdPreviewRoute,
  }

const WorkspaceWorkspaceIdRouteRouteWithChildren =
  WorkspaceWorkspaceIdRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceWorkspaceIdRouteRoute: WorkspaceWorkspaceIdRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthIndexRoute: AuthIndexRoute,
  funnelFIdRoute: funnelFIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
