/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "BILLING": {
      "managedServiceMonthlyPriceId": string
      "managedServiceProductId": string
      "managedServiceYearlyPriceId": string
      "standard100KMonthlyPriceId": string
      "standard100KVisitorsPriceId": string
      "standard100KYearlyPriceId": string
      "standard1MMonthlyPriceId": string
      "standard1MVisitorsPriceId": string
      "standard1MYearlyPriceId": string
      "standard250KMonthlyPriceId": string
      "standard250KVisitorsPriceId": string
      "standard250KYearlyPriceId": string
      "standard25KMonthlyPriceId": string
      "standard25KVisitorsPriceId": string
      "standard25KYearlyPriceId": string
      "standard2MMonthlyPriceId": string
      "standard2MVisitorsPriceId": string
      "standard2MYearlyPriceId": string
      "standard500KMonthlyPriceId": string
      "standard500KVisitorsPriceId": string
      "standard500KYearlyPriceId": string
      "standard50KMonthlyPriceId": string
      "standard50KVisitorsPriceId": string
      "standard50KYearlyPriceId": string
      "standard5KMonthlyPriceId": string
      "standard5KVisitorsPriceId": string
      "standard5KYearlyPriceId": string
      "standardProductId": string
      "type": "sst.sst.Linkable"
      "visitorMeterId": string
    }
    "CLOUDFLARE_R2_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_SSL_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ZONE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STORAGE_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "TINYBIRD_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AnalyticsQueue": cloudflare.Queue
    "AnalyticsWorker": cloudflare.Service
    "AuthApi": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
    "Storage": cloudflare.R2Bucket
  }
}

import "sst"
export {}