/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "CLOUDFLARE_R2_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_SSL_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ZONE_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SHOPIFY_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STORAGE_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "TINYBIRD_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AnalyticsQueue": cloudflare.Queue
    "AnalyticsWorker": cloudflare.Service
    "AuthApi": cloudflare.Service
    "AuthStorage": cloudflare.KVNamespace
    "Storage": cloudflare.R2Bucket
    "StorageWorker": cloudflare.Service
  }
}

import "sst"
export {}